import { IProduct } from "../model/IProduct";
import { Product } from "../model/Product";

export const products: IProduct[] = [
    {
        id: 100001,
        internalName: "mk750_coolermaster",
        title: "Cooler Master MK750",
        price: 499.99,
        description: "Mechaniczna klawiatura gamingowa z podświetleniem RGB i przełącznikami Cherry MX.",
        category: Product.Keyboard,
        image: "mk750.png",
        rating: { rate: 5, count: 321 },
        onSale: true,
        salePrice: 429.99,
    },
    {
        id: 100002,
        internalName: "logitech_g502",
        title: "Logitech G502 Hero",
        price: 269.0,
        description: "Zaawansowana mysz gamingowa z czujnikiem HERO i programowalnymi przyciskami.",
        category: Product.Mouse,
        image: "g502.jpg",
        rating: { rate: 4.8, count: 512 },
    },
    {
        id: 100003,
        internalName: "steelseries_qck",
        title: "SteelSeries QcK Medium",
        price: 69.99,
        description: "Precyzyjna podkładka pod mysz z mikroteksturowaną powierzchnią.",
        category: Product.Mousepad,
        image: "/images/products/qck.jpg",
        rating: { rate: 4.5, count: 198 },
    },
    {
        id: 100004,
        internalName: "hyperx_quadcast",
        title: "HyperX QuadCast",
        price: 599.0,
        description: "Profesjonalny mikrofon pojemnościowy z czterema wzorcami nagrywania i RGB.",
        category: Product.Microphone,
        image: "/images/products/quadcast.jpg",
        rating: { rate: 4.6, count: 287 },
        onSale: true,
        salePrice: 499.0,
    },
    {
        id: 100005,
        internalName: "usb_hub_ugreen",
        title: "Ugreen USB 3.0 Hub",
        price: 89.99,
        description: "Rozszerz swój komputer o cztery porty USB 3.0 z szybkim transferem danych.",
        category: Product.Accessories,
        image: "/images/products/ugreen_hub.jpg",
        rating: { rate: 4.4, count: 104 },
    },
    {
        id: 100006,
        internalName: "razer_blackwidow_v4",
        title: "Razer BlackWidow V4",
        price: 699.0,
        description: "Klawiatura mechaniczna z dedykowanymi makrami, podpórką pod nadgarstki i RGB.",
        category: Product.Keyboard,
        image: "/images/products/blackwidow.jpg",
        rating: { rate: 2, count: 402 },
    },
    {
        id: 100007,
        internalName: "glorious_model_o",
        title: "Glorious Model O",
        price: 329.0,
        description: "Ultralekka mysz gamingowa z kablem typu ultraflex i precyzyjnym sensorem.",
        category: Product.Mouse,
        image: "/images/products/model_o.jpg",
        rating: { rate: 4.9, count: 1340 },
    },
    {
        id: 100008,
        internalName: "endgame_pad",
        title: "Endgame Gear MPJ-890",
        price: 119.99,
        description: "Duża podkładka pod mysz i klawiaturę o niskim tarciu i precyzyjnej powierzchni.",
        category: Product.Mousepad,
        image: "/images/products/mpj890.jpg",
        rating: { rate: 4.6, count: 87 },
    },
    {
        id: 100009,
        internalName: "elgato_wave_3",
        title: "Elgato Wave:3",
        price: 679.0,
        description: "Mikrofon USB klasy premium dla streamerów z technologią Clipguard.",
        category: Product.Microphone,
        image: "/images/products/wave3.jpg",
        rating: { rate: 4.8, count: 415 },
        onSale: true,
        salePrice: 589.0,
    },
    {
        id: 100010,
        internalName: "logitech_usb_switch",
        title: "Logitech USB Switch",
        price: 149.99,
        description: "Przełącznik USB pozwalający sterować wieloma urządzeniami jednym zestawem peryferiów.",
        category: Product.Accessories,
        image: "/images/products/usb_switch.jpg",
        rating: { rate: 4.3, count: 59 },
    },
    {
        id: 100011,
        internalName: "keychron_k6",
        title: "Keychron K6 Wireless",
        price: 439.0,
        description: "Bezprzewodowa klawiatura 65% z Bluetooth i podświetleniem RGB.",
        category: Product.Keyboard,
        image: "/images/products/keychron_k6.jpg",
        rating: { rate: 4.5, count: 230 },
    },
    {
        id: 100012,
        internalName: "viper_mini",
        title: "Razer Viper Mini",
        price: 149.0,
        description: "Kompaktowa i lekka mysz gamingowa z podświetleniem Chroma.",
        category: Product.Mouse,
        image: "/images/products/viper_mini.jpg",
        rating: { rate: 4.6, count: 318 },
        onSale: true,
        salePrice: 119.0,
    },
    {
        id: 100013,
        internalName: "xraypad_thor",
        title: "X-Raypad Thor 390x280",
        price: 89.0,
        description: "Szybka i precyzyjna podkładka z niskim oporem, idealna do FPS.",
        category: Product.Mousepad,
        image: "/images/products/thor_pad.jpg",
        rating: { rate: 4.4, count: 72 },
    },
    {
        id: 100014,
        internalName: "fifine_k690",
        title: "Fifine K690",
        price: 299.0,
        description: "Mikrofon USB z czterema trybami pracy i kompatybilnością z Windows i Mac.",
        category: Product.Microphone,
        image: "/images/products/k690.jpg",
        rating: { rate: 4.5, count: 143 },
    },
    {
        id: 100015,
        internalName: "bungee_cable_holder",
        title: "BenQ Zowie CAMADE II",
        price: 129.99,
        description: "Organizer przewodu myszy dla lepszej kontroli i czystości stanowiska.",
        category: Product.Accessories,
        image: "/images/products/camade.jpg",
        rating: { rate: 4.6, count: 94 },
    },
];
