import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./assets/styles/index.scss";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";
import { Providers } from "./context/ContextProviders";
import { Toaster } from "react-hot-toast";

const rajdhani = Rajdhani({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // możesz dobrać inne
  display: 'swap',
})

export const metadata: Metadata = {
  title: "GameZone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rajdhani.className} mainbody`}>
        <Providers>
          <Navbar />
          <Toaster position="bottom-center" toastOptions={{ style: { background: "#ff2e88", color: "white" } }} />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
