import type { Metadata } from "next";
import "./assets/styles/index.scss";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";
import { Providers } from "./context/ContextProviders";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "GameZone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`mainbody`}>
        <Providers>
          <Navbar />
          <Toaster
            position="bottom-right"
            toastOptions={{ style: { background: "#ff2e88", color: "white" } }}
          />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
